<a href="https://colab.research.google.com/github/Rerzd/Ciencia_Datos_intro/blob/main/dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Dataframe
##1. columnas (features - caracteristicas)
##2. Filas (registros)

In [ ]:
import numpy as np
import pandas as pd

#convertir de lista a dataframe

ventas = pd.Series([22,15,7])
ventas


0    22
1    15
2     7
dtype: int64

In [ ]:
ventas=pd.Series([22,15,70], index=["Enero", "Febrero", "Marzo"]) #Asociar los números de ventas con un mes
ventas

Enero      22
Febrero    15
Marzo      70
dtype: int64

In [ ]:
# Para conocer las ventas de enero
ventas["Enero"]

22

In [ ]:
ventas.dtype

dtype('int64')

In [ ]:
ventas.index

Index(['Enero', 'Febrero', 'Marzo'], dtype='object')

In [ ]:
#para conocer valores de feature
ventas.values

array([22, 15,  7])

In [ ]:
#nombrar el index
ventas.name= "Ventas del 2025"
ventas
#categorizar el index
ventas.index.name="Meses"
ventas

Meses
Enero      22
Febrero    15
Marzo      70
Name: Ventas del 2025, dtype: int64

In [ ]:
ventas.shape

(3,)

## Conversión de diccionarios a dataframe

###Diccionarios
1. no tienen identación
2. poseen clave única,y un valor asociado con la clave
3. son mutables

In [ ]:

diccionario = {"Enero":22, "Febrero":15, "Marzo":70}
type(diccionario)

# diccionario a dataframe

ventas_1=pd.Series(diccionario) #no olvidar la mayúscula en 'Series' malditasea
ventas_1

Rigel = pd.Series(diccionario, index = ["Enero", "Febrero", "Marzo", "Abril"])
Rigel

Enero      22.0
Febrero    15.0
Marzo      70.0
Abril       NaN
dtype: float64

In [ ]:
medidas = pd.DataFrame(
            {"Humedad":[41,22,30,80],
             "Salinidad":[22,15,30,80],
              "Sensórica": ["si", "no", "no", "no"],
              "Acidez": ["alta", "media", "baja", "mbaja"],
              "PH": [1,7,14,13]},
            index = ["La Bachata", "La salsa" , "El merengue", "El vallenato"]
           )
medidas

Humedad  Salinidad Sensórica Acidez  PH
La Bachata         41         22        si   alta   1
La salsa           22         15        no  media   7
El merengue        30         30        no   baja  14
El vallenato       80         80        no  mbaja  13

from matplotlib import pyplot as plt
medidas['Humedad'].plot(kind='hist', bins=20, title='Humedad')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
medidas['Salinidad'].plot(kind='hist', bins=20, title='Salinidad')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
medidas['PH'].plot(kind='hist', bins=20, title='PH')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
medidas.groupby('Sensórica').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
medidas.groupby('Acidez').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
medidas.plot(kind='scatter', x='Humedad', y='Salinidad', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
medidas.plot(kind='scatter', x='Salinidad', y='PH', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
medidas['Humedad'].plot(kind='line', figsize=(8, 4), title='Humedad')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
medidas['Salinidad'].plot(kind='line', figsize=(8, 4), title='Salinidad')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
medidas['PH'].plot(kind='line', figsize=(8, 4), title='PH')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Acidez'].value_counts()
    for x_label, grp in medidas.groupby('Sensórica')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Sensórica')
_ = plt.ylabel('Acidez')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(medidas['Sensórica'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(medidas, x='Humedad', y='Sensórica', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(medidas['Acidez'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(medidas, x='Humedad', y='Acidez', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(medidas['Sensórica'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(medidas, x='Salinidad', y='Sensórica', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(medidas['Acidez'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(medidas, x='Salinidad', y='Acidez', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
medidas.index.name="mata"
medidas
medidas.Humedad

mata
La Bachata      41
La salsa        22
El merengue     30
El vallenato    80
Name: Humedad, dtype: int64

In [ ]:
medidas.Humedad, medidas.Salinidad #lo mismo que lo de abajo pero mas feo
medidas.dtypes #conocer tipo de objeto

Humedad       int64
Salinidad     int64
Sensórica    object
Acidez       object
PH            int64
dtype: object

In [ ]:
medidas[["Humedad", "Salinidad"]] # Se utiliza para segmentar las listas

Humedad  Salinidad
mata                            
La Bachata         41         22
La salsa           22         15
El merengue        30         30
El vallenato       80         80

In [ ]:
medidas.axes #muestra nombres de filas y columnas

[Index(['La Bachata', 'La salsa', 'El merengue', 'El vallenato'], dtype='object', name='mata'),
 Index(['Humedad', 'Salinidad', 'Sensórica', 'Acidez', 'PH'], dtype='object')]

In [ ]:
medidas.values

array([[41, 22, 'si', 'alta', 1],
       [22, 15, 'no', 'media', 7],
       [30, 30, 'no', 'baja', 14],
       [80, 80, 'no', 'mbaja', 13]], dtype=object)

In [ ]:
medidas.shape #longitud de la lista

(4, 5)

###Ejercicios
Dados los siguientes diccionarios, convertirlos en datagramas y usar todos los métodos aprendidos:

```
elementos={"número atómico":[1,6,47,88],
"Masa atómica":[1,12,107,226],
"Familia":["No metal","No metal","Metal","Metal"]}
```
Agregar como registros el nombre de los elementos

2. Convertir en dataframe el siguiente conjunto de medidas
```
medida_2020={"Ag":2,"Au":5,"Cu":3,"Pt":2}
medida_2021={"Ag":4,"Au":3,"Cu":6,"Pt":1}
medida_2022={"Ag":8,"Au":2,"Cu":15,"Pt":0}
medida_2023={"Ag":5,"Au":1,"Cu":0,"Pt":5}
medida_2024={"Ag":7,"Au":0,"Cu":3,"Pt":2}
medida_20205={"Ag":9,"Au":1,"Cu":3,"Pt":5}
```
Tenga en cuenta que los registros son los meses de medida y las features deben ser los elementos

In [ ]:
elementos=pd.DataFrame(
            {"número_atómico":[1,6,47,88],
             "Masa_atómica":[1,12,107,226],
             "Familia":["No metal","No metal","Metal","Metal"]},
            index = ["H","C","Ag","Pt"])
elementos

número_atómico  Masa_atómica   Familia
H                1             1  No metal
C                6            12  No metal
Ag              47           107     Metal
Pt              88           226     Metal

In [ ]:
elementos.index.name = "tipo_elemento"
elementos
elementos.número_atómico

tipo_elemento
H      1
C      6
Ag    47
Pt    88
Name: número_atómico, dtype: int64

In [ ]:
elementos[["número_atómico", "Masa_atómica"]]

número_atómico  Masa_atómica
tipo_elemento                              
H                           1             1
C                           6            12
Ag                         47           107
Pt                         88           226

In [ ]:
elementos.axes

[Index(['H', 'C', 'Ag', 'Pt'], dtype='object', name='tipo_elemento'),
 Index(['número_atómico', 'Masa_atómica', 'Familia'], dtype='object')]

In [ ]:
elementos.values

array([[1, 1, 'No metal'],
       [6, 12, 'No metal'],
       [47, 107, 'Metal'],
       [88, 226, 'Metal']], dtype=object)

In [ ]:
elementos.shape

(4, 3)

In [ ]:
medida = pd.DataFrame(
        {"medida_2020":{"Ag":2,"Au":5,"Cu":3,"Pt":2},
         "medida_2021":{"Ag":4,"Au":3,"Cu":6,"Pt":1},
         "medida_2022":{"Ag":8,"Au":2,"Cu":15,"Pt":0},
         "medida_2023":{"Ag":5,"Au":1,"Cu":0,"Pt":5},
         "medida_2024":{"Ag":7,"Au":0,"Cu":3,"Pt":2},
         "medida_20205":{"Ag":9,"Au":1,"Cu":3,"Pt":5}},
        index = ["Ag", "Au", "Cu", "Pt"]
)
medida

medida_2020  medida_2021  medida_2022  medida_2023  medida_2024  \
Ag            2            4            8            5            7   
Au            5            3            2            1            0   
Cu            3            6           15            0            3   
Pt            2            1            0            5            2   

    medida_20205  
Ag             9  
Au             1  
Cu             3  
Pt             5

In [ ]:
medida.index.name = "elemento"
medida
medida.medida_2020

elemento
Ag    2
Au    5
Cu    3
Pt    2
Name: medida_2020, dtype: int64

In [ ]:
medida[["medida_2020", "medida_2021"]]

medida_2020  medida_2021
elemento                          
Ag                  2            4
Au                  5            3
Cu                  3            6
Pt                  2            1

In [ ]:
medida.values

array([[ 2,  4,  8,  5,  7,  9],
       [ 5,  3,  2,  1,  0,  1],
       [ 3,  6, 15,  0,  3,  3],
       [ 2,  1,  0,  5,  2,  5]])

In [ ]:
medida.medida_2020 , medida.medida_2021
medida.dtypes

medida_2020     int64
medida_2021     int64
medida_2022     int64
medida_2023     int64
medida_2024     int64
medida_20205    int64
dtype: object

In [ ]:
medida.shape

(4, 6)

In [ ]:
medida.axes

[Index(['Ag', 'Au', 'Cu', 'Pt'], dtype='object', name='elemento'),
 Index(['medida_2020', 'medida_2021', 'medida_2022', 'medida_2023',
        'medida_2024', 'medida_20205'],
       dtype='object')]